remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: EventShare Documentation
description: Privacy Policy and Data Deletion Instructions for EventShare App
show_downloads: false
